### ISSUE TITLE
Consider using foundry profiles

### ISSUE THREAD

**Issue by pakim249CAL** [morpho-org/morpho-aavev3-optimizer#806]
One profile that the makefile will use to compile with --via-ir and the default profile to compile and test without --via-ir.

**Comment by Rubilmax** [comment]
Is this abandoned?

**Comment by MerlinEgalite** [comment]
Not working on it on my side

**Comment by pakim249CAL** [comment]
> Is this abandoned?

For now. I tried for a bit but couldn't come up with a satisfactory working solution and am working on other priorities for now. I may come back to this eventually.
